version: "3.9"  # Specify the Docker Compose version

services:
  postgres:
    image: postgres:17  # PostgreSQL 17 image
    container_name: postgres17  # Name of the container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bude_transactions
    ports:
      - "5432:5432"  # Map port 5432 of the container to port 5432 on your host
    volumes:
      - ./sql:/docker-entrypoint-initdb.d  # Mount the `sql/` folder
      - postgres_data:/var/lib/postgresql/data  # Persist data using a named volume

volumes:
  postgres_data: